name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create properties.db.inc.php
      run: |
        echo '<?php' > properties.db.inc.php
        echo '' >> properties.db.inc.php
        echo '/**' >> properties.db.inc.php
        echo ' * Renomeie este arquivo para properties.db.inc.php no seu ambiente local' >> properties.db.inc.php
        echo ' * Aponte as credenciais para os bancos de desenvolvimento' >> properties.db.inc.php
        echo ' */' >> properties.db.inc.php
        echo '' >> properties.db.inc.php
        echo '$DB_APPLICATION = array();' >> properties.db.inc.php
        echo '' >> properties.db.inc.php
        echo '$DB_APPLICATION["portaldofornecedor"] = array(' >> properties.db.inc.php
        echo '    "type" => "desenvolvimento",' >> properties.db.inc.php
        echo '    "db" => "mysql",' >> properties.db.inc.php
        echo '    "server" => "${{ secrets.MYSQL_HOST }}",' >> properties.db.inc.php
        echo '    "port" => "3306",' >> properties.db.inc.php
        echo '    "name" => "portaldofornecedor",' >> properties.db.inc.php
        echo '    "user" => "${{ secrets.MYSQL_USER_PORTALDOFORNECEDOR }}",' >> properties.db.inc.php
        echo '    "password" => "${{ secrets.MYSQL_PASSWORD_PORTALDOFORNECEDOR }}"' >> properties.db.inc.php
        echo ');' >> properties.db.inc.php
        echo '' >> properties.db.inc.php
        echo '$DB_APPLICATION["administrativo"] = array(' >> properties.db.inc.php
        echo '    "type" => "desenvolvimento",' >> properties.db.inc.php
        echo '    "db" => "mysql",' >> properties.db.inc.php
        echo '    "server" => "${{ secrets.MYSQL_HOST }}",' >> properties.db.inc.php
        echo '    "port" => "3306",' >> properties.db.inc.php
        echo '    "name" => "administrativo",' >> properties.db.inc.php
        echo '    "user" => "${{ secrets.MYSQL_USER_ADMINISTRATIVO }}",' >> properties.db.inc.php
        echo '    "password" => "${{ secrets.MYSQL_PASSWORD_ADMINISTRATIVO }}"' >> properties.db.inc.php
        echo ');' >> properties.db.inc.php
      
    
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      uses: docker/build-push-action@v4.1.1
      env:
        tagVersion: "${{ github.run_number }}"
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # path to dockerfile
        file: ./Dockerfile
        # List of tags
        tags: |
          renatoaugustofs/portal:latest
          renatoaugustofs/portal:v${{ env.tagVersion }}
        # Push to docker hub?
        push: true

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.10
      with:
        app-name: teste-ci-cd-portal
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PORTAL_CI_CD_TESTE }}
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: renatoaugustofs/portal:v${{ github.run_number }}

    
      
